title: Space Finder
email: "d.knox@kent.ac.uk"
description: >-
  Spacefinder includes detailed descriptions of spaces,
  filters based on space characteristics, and navigation
  via a map.
environment: production
baseurl: ""
url: "https://danielknox.github.io/spacefinder/"
host: "localhost"
google_analytics: ""
photo_dir: "/assets/photos/"
lang: "en"
dc:
  creator: ""
  dateCreated: ""
  dateModified: ""
  publisher: ""
  spatialCoverage: ""
  types:
    - "InteractiveResource"
  subjects:
    - "Digital mapping"
    - "College Campuses"
terms:
  url: ""
  text: ""
  shorttext: ""
foi:
  url: ""
  text: ""
  shorttext: ""
copyright: ""
sass:
  style: compressed
plugins:
  - jekyll-feed
